### ISSUE TITLE
Kurang kolom kota

### ISSUE THREAD

**Issue by bimanugrahaa** [admiralkuznetsov45/SistemVaksinAPI#2]
https://github.com/admiralkuznetsov45/SistemVaksinAPI/blob/f3e1dda271fde2a84b5f69b6bff9c19655585f2f/features/faskes/data/record.go#L9-L17

https://github.com/admiralkuznetsov45/SistemVaksinAPI/blob/f3e1dda271fde2a84b5f69b6bff9c19655585f2f/features/faskes/entity.go#L3-L10

Buat yang faskes ternyata kurang kolom kota. Tolong update buat bagian _entity_, _record_, _dto response_, sama _dto request_ ya. Makasih

**Comment by admiralkuznetsov45** [comment]
Sudah kutambahkan
